# Generated by Django 3.1.7 on 2021-03-29 12:18

import model_utils.fields
from django.db import migrations


def set_default_timezone(apps, schema_editor):
    Member = apps.get_model("ctfhub", "Member")
    for member in Member.objects.all():
        member.timezone = "UTC"
        member.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0005_auto_20210204_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="timezone",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                default="UTC",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.RunPython(set_default_timezone),
    ]
