# Generated by Django 4.2.2 on 2023-06-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0008_remove_challenge_whiteboard_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="assigned_members",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_challenges", to="ctfhub.member"
            ),
        ),
    ]
