# Generated by Django 4.2.2 on 2023-06-28 22:53

import ctfhub.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0009_challenge_working_on_it_alter_challengefile_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="working_on_it",
        ),
        migrations.AlterField(
            model_name="challengefile",
            name="file",
            field=models.FileField(
                null=True,
                upload_to="files/",
                validators=[ctfhub.validators.challenge_file_max_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="media/"),
        ),
    ]
