# Generated by Django 4.2.2 on 2023-06-28 22:53

import django.core.files.storage
from django.db import migrations, models

import ctfhub.helpers
import ctfhub.validators


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0009_add_challenge_assigned_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengefile",
            name="file",
            field=models.FileField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads/", location="/code/uploads"
                ),
                upload_to=ctfhub.helpers.get_challenge_upload_path,
                validators=[ctfhub.validators.challenge_file_max_size_validator],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads/", location="/code/uploads"
                ),
                upload_to="media/",
            ),
        ),
    ]
