# Generated by Django 4.2.2 on 2023-06-27 18:17

from django.db import migrations, models


from ctfhub.models import Member


def forwards_func(apps, schema_editor):
    MemberModel = apps.get_model("ctfhub", "Member")

    for member in MemberModel.objects.all():
        member.status = (
            Member.StatusType.MEMBER
            if member.old_status == "member"
            else Member.StatusType.GUEST
        )
        member.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0011_ctf_visibility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="status",
            new_name="old_status",
        ),
        migrations.AddField(
            model_name="member",
            name="status",
            field=models.IntegerField(choices=[(0, "Member"), (1, "Guest")], default=0),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name="member",
            name="old_status",
        ),
    ]
