# Generated by Django 4.2.2 on 2023-06-29 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0010_alter_challengefile_file_and_more"),
        ("ctfhub", "0016_alter_member_timezone"),
    ]

    operations = []
