# Generated by Django 4.2.2 on 2023-06-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0017_merge_20230629_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Member"), (1, "Guest"), (2, "Inactive")], default=0
            ),
        ),
    ]
