# Generated by Django 4.2.2 on 2023-07-04 16:06

import ctfhub.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ctfhub", "0020_alter_member_hedgedoc_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/uploads/", location="/code/uploads"
                ),
                upload_to="media/",
                validators=[ctfhub.validators.challenge_file_max_size_validator],
            ),
        ),
    ]
