version: '3'

services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${CTFPAD_DB_NAME}
      - POSTGRES_USER=${CTFPAD_DB_USER}
      - POSTGRES_PASSWORD=${CTFPAD_DB_PASSWORD}
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - ctfpad
    restart: always

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:alpine
    links:
      - "postgres:db"
    env_file:
      - .env
    environment:
      - CMD_DB_URL=postgres://${CTFPAD_DB_USER}:${CTFPAD_DB_PASSWORD}@${CTFPAD_DB_HOST}:${CTFPAD_DB_PORT}/${CTFPAD_DB_NAME}
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_FREEURL=true
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_DOMAIN=${CTFPAD_HEDGEDOC_DOMAIN}
      - CMD_PORT=${CTFPAD_HEDGEDOC_PORT}
      - CMD_URL_ADDPORT=true
      - CMD_PROTOCOL_USESSL=false
    networks:
      - ctfpad
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./volumes/hedgedoc-public-uploads:/hedgedoc/public/uploads

  ctfpad:
    # build: https://github.com/hugsy/ctfpad.git#master
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - "postgres:db"
    env_file:
      - .env
      # - .env.proxy # Uncomment if using a proxy
    depends_on:
      - postgres
      - hedgedoc
      - excalidraw
    ports:
      - 8000:8000
    networks:
      - ctfpad
    restart: always
    volumes:
      - ./volumes/uploads:/code/uploads
      - ./ctfpad:/code/ctfpad
      - ./ctftools:/code/ctftools

  excalidraw:
    # https://github.com/excalidraw/excalidraw/blob/master/docker-compose.yml
    build:
      context: https://github.com/excalidraw/excalidraw.git#master
      args:
        - NODE_ENV=${EXCALIDRAW_NODE_ENV}
    networks:
      - ctfpad
      - excalidraw
    ports:
      - 3001:80
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${EXCALIDRAW_NODE_ENV}
    healthcheck:
      disable: true
    stdin_open: true

  excalidraw-room:
    image: excalidraw/excalidraw-room
    restart: always
    networks:
      - excalidraw
    # ports:
    #   - 8081:80

  excalidraw-storage-backend:
    # repo https://gitlab.com/kiliandeca/excalidraw-storage-backend
    image: kiliandeca/excalidraw-storage-backend
    networks:
      - excalidraw
    # ports:
    #   - 8082:8080
    restart: always
    env_file:
      - .env
    environment:
      STORAGE_URI: redis://:${REDIS_PASSWORD}@redis:6379
      STORAGE_TTL: 2592000000
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - excalidraw
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis-vol:/data

networks:
  ctfpad:
    driver: bridge

  excalidraw:
    driver: bridge

volumes:
  postgres-vol:
  redis-vol:
