#
# FIRST OFF CHANGE ALL THE CREDENTIALS !!!!
#
# Then run
#
# $ docker-compose up --build
#

version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=ctfpad
      - POSTGRES_USER=ctfpad
      - POSTGRES_PASSWORD=tookahlaiphee2KieTeeg5ooxutang4o   # Change here
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      backend:
    restart: unless-stopped


  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.6.0
    environment:
      - CMD_DB_URL=postgres://ctfpad:tookahlaiphee2KieTeeg5ooxutang4o@db:5432/ctfpad    # Change here
      - CMD_DOMAIN=localhost
      - CMD_PORT=3000
      - CMD_COOKIE_POLICY=none
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_FREEURL=true
      # Uncomment to use nginx as a HTTPS reverse proxy
      #- CMD_DOMAIN=ctfpad.mydomain.com:3443
      #- CMD_URL_ADDPORT=false
      #- CMD_PROTOCOL_USESSL=true
    ports:
      - "3000:3000"
    networks:
      backend:
    restart: unless-stopped
    depends_on:
      - db


  ctfpad:
    build: https://github.com/hugsy/ctfpad.git#master
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - HEDGEDOC_URL=http://localhost:3000
      - CTFPAD_HOSTNAME=localhost
      # Or replace with below instead to use nginx as a HTTPS reverse proxy
      #- HEDGEDOC_URL=https://ctfpad.mydomain.com:3443
      #- CTFPAD_HOSTNAME=ctfpad.mydomain.com
      - CTFPAD_DB_NAME=ctfpad
      - CTFPAD_DB_USER=ctfpad
      - CTFPAD_DB_PASSWORD=tookahlaiphee2KieTeeg5ooxutang4o # Change here
      - CTFPAD_DB_HOST=db
      - CTFPAD_DB_PORT=5432
      # Uncomment and adjust to enable the password recovery feature by email
      #- CTFPAD_EMAIL_SERVER_HOST=smtp.gmail.com # or mailgun, or sendgrid etc.
      #- CTFPAD_EMAIL_SERVER_PORT=587
      #- CTFPAD_EMAIL_USERNAME=myaccount
      #- CTFPAD_EMAIL_PASSWORD=mypassword
    depends_on:
      - db
      - hedgedoc
    ports:
      - "8000:8000"
    volumes:
      - uploads:/code/uploads
    networks:
      backend:
    restart: unless-stopped


  nginx:
    image: nginx:1.19.5
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/certs:/etc/nginx/certs
    ports:
      - 8443:8443
      - 3443:3443
    depends_on:
      - ctfpad
    networks:
      backend:
    restart: unless-stopped

networks:
  backend:

volumes:
  db:
  uploads:
