version: '3'

services:

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${CTFPAD_DB_NAME}
      - POSTGRES_USER=${CTFPAD_DB_USER}
      - POSTGRES_PASSWORD=${CTFPAD_DB_PASSWORD}
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - ctfpad
    restart: always

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:alpine
    links:
      - "postgres:db"
    env_file:
      - .env
    environment:
      - CMD_DB_URL=postgres://${CTFPAD_DB_USER}:${CTFPAD_DB_PASSWORD}@${CTFPAD_DB_HOST}:${CTFPAD_DB_PORT}/${CTFPAD_DB_NAME}
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_FREEURL=true
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_DOMAIN=${CTFPAD_HEDGEDOC_DOMAIN}
      - CMD_PORT=${CTFPAD_HEDGEDOC_PORT}
      - CMD_URL_ADDPORT=true
      - CMD_PROTOCOL_USESSL=false
    networks:
      - ctfpad
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./volumes/upload/hedgedoc:/hedgedoc/public/uploads

  ctfpad:
    # build: https://github.com/hugsy/ctfpad.git#master
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - "postgres:db"
    env_file:
      - .env
      # - .env.proxy # Uncomment if using a proxy
    depends_on:
      - postgres
      - hedgedoc
    ports:
      - 8000:8000
    networks:
      - ctfpad
    restart: always
    volumes:
      - ./volumes/upload/ctfpad:/code/uploads
      - ./ctfpad:/code/ctfpad
      - ./ctftools:/code/ctftools

networks:
  ctfpad:
    driver: bridge

volumes:
  postgres-vol:
