version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - ctfpad
    restart: always


  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:alpine
    environment:
      - CMD_DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_FREEURL=true
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      # Uncomment to use nginx as a HTTPS reverse proxy
      - CMD_DOMAIN=${CMD_DOMAIN}
      - CMD_URL_ADDPORT=${CMD_URL_ADDPORT}
      - CMD_PROTOCOL_USESSL=${CMD_PROTOCOL_USESSL}
    ports:
      - 3000:3000
    networks:
      - ctfpad
    restart: always
    depends_on:
      - db
    volumes:
      - ./volumes/hedgedoc-public-uploads:/hedgedoc/public/uploads


  ctfpad:
    # build: https://github.com/hugsy/ctfpad.git#master
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=${CTFPAD_DEBUG}
      - HEDGEDOC_URL=${HEDGEDOC_URL}
      - EXCALIDRAW_URL=${EXCALIDRAW_URL}
      - CTFPAD_HOSTNAME=${CTFPAD_HOSTNAME}
      - CTFPAD_PORT=${CTFPAD_PORT}
      - CTFPAD_USE_SSL=${CTFPAD_USE_SSL}
      - CTFPAD_DB_NAME=${POSTGRES_DB}
      - CTFPAD_DB_USER=${POSTGRES_USER}
      - CTFPAD_DB_PASSWORD=${POSTGRES_PASSWORD}
      - CTFPAD_DB_HOST=db
      - CTFPAD_DB_PORT=5432
      - CTFPAD_SECRET_KEY=${CTFPAD_SECRET_KEY}
      - USE_INTERNAL_HEDGEDOC=${USE_INTERNAL_HEDGEDOC}
      # Uncomment (and customize) below to enable the password recovery feature by email
      #- CTFPAD_EMAIL_SERVER_HOST=smtp.gmail.com # or mailgun, or sendgrid etc.
      #- CTFPAD_EMAIL_SERVER_PORT=587
      #- CTFPAD_EMAIL_USERNAME=myaccount
      #- CTFPAD_EMAIL_PASSWORD=mypassword
      # Uncomment (and customize) below to enable Discord webhook notifications
      #- CTFPAD_DISCORD_WEBHOOK_URL=
    depends_on:
      - db
      - hedgedoc
      - excalidraw
    ports:
      - 8000:8000
    networks:
      - ctfpad
    restart: always
    volumes:
      - ./volumes/uploads:/code/uploads
      - ./ctfpad:/code/ctfpad
      - ./ctftools:/code/ctftools

  excalidraw:
    build:
      context: ./src-repos/excalidraw
      target: production
    container_name: excalidraw
    networks:
      - ctfpad
    ports:
      - 8080:80
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      disable: true

  excalidraw-room:
    image: excalidraw/excalidraw-room
    restart: always
    networks:
      - ctfpad
    ports:
      - 8081:80

  excalidraw-storage-backend:
    # repo https://gitlab.com/kiliandeca/excalidraw-storage-backend
    image: kiliandeca/excalidraw-storage-backend
    networks:
      - ctfpad
    ports:
      - 8082:8080
    restart: always
    environment:
      STORAGE_URI: redis://:${REDIS_PASSWORD}@redis:6379
      STORAGE_TTL: 2592000000
    depends_on:
      - redis


  redis:
    image: redis
    networks:
      - ctfpad
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - ./volumes/redis:/data

networks:
  ctfpad:
    driver: bridge
