version: '3'
services:
  nginx:
    image: nginx:latest
    networks:
      - ctfhub
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ctfhub
      - hedgedoc
      - excalidraw
      - excalidraw-room
      - excalidraw-storage-backend
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/certs:/etc/nginx/certs
    restart: always

