version: '3'
services:
  nginx:
    image: nginx:latest
    networks:
      - ctfhub
    ports:
      - 80:80 # change here the public port to your own setup
      - 443:443 # change here the public port to your own setup
    depends_on:
      - ctfhub
      - hedgedoc
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/certs:/etc/nginx/certs
    restart: always
