name: "Run tests"

on:
  workflow_dispatch:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo POSTGRES_DB=ctfpad >> $GITHUB_ENV
          echo POSTGRES_USER=ctfpad >> $GITHUB_ENV
          echo POSTGRES_PASSWORD=ctfpad >> $GITHUB_ENV

          echo CTFPAD_PROTOCOL=http >> $GITHUB_ENV
          echo CTFPAD_DOMAIN=localhost >> $GITHUB_ENV
          echo CTFPAD_PORT=8000 >> $GITHUB_ENV
          echo CTFPAD_DB_NAME=ctfpad >> $GITHUB_ENV
          echo CTFPAD_DB_USER=ctfpad >> $GITHUB_ENV
          echo CTFPAD_DB_PASSWORD=ctfpad >> $GITHUB_ENV
          echo CTFPAD_DB_HOST=localhost >> $GITHUB_ENV
          echo CTFPAD_DB_PORT=5432 >> $GITHUB_ENV
          echo CTFPAD_HEDGEDOC_URL=http://localhost:3000 >> $GITHUB_ENV
          echo CTFPAD_HEDGEDOC_IS_INTERNAL=1 >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'

      - run: |
          python -m pip install pip --user --upgrade
          python -m pip install -r requirements.txt --user --upgrade
          python manage.py migrate
          python manage.py test ctfpad
