name: "Run tests"

on:
  workflow_dispatch:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ctfpad
          POSTGRES_USER: ctfpad
          POSTGRES_PASSWORD: ctfpad
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      hedgedoc:
        image: quay.io/hedgedoc/hedgedoc:alpine
        env:
          CMD_DB_URL: postgres://ctfpad:ctfpad@localhost:5432/ctfpad
          CMD_ALLOW_ANONYMOUS: false
          CMD_ALLOW_FREEURL: true
          CMD_IMAGE_UPLOAD_TYPE: filesystem
          CMD_DOMAIN: localhost
          CMD_PORT: 3000
          CMD_URL_ADDPORT: true
          CMD_PROTOCOL_USESSL: false
        ports:
          - 3000:3000
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo CTFPAD_PROTOCOL=http >> $GITHUB_ENV
          echo CTFPAD_DOMAIN=localhost >> $GITHUB_ENV
          echo CTFPAD_PORT=8000 >> $GITHUB_ENV
          echo CTFPAD_DB_NAME=ctfpad >> $GITHUB_ENV
          echo CTFPAD_DB_USER=ctfpad >> $GITHUB_ENV
          echo CTFPAD_DB_PASSWORD=ctfpad >> $GITHUB_ENV
          echo CTFPAD_DB_HOST=localhost >> $GITHUB_ENV
          echo CTFPAD_DB_PORT=5432 >> $GITHUB_ENV
          echo CTFPAD_HEDGEDOC_URL=http://localhost:3000 >> $GITHUB_ENV
          echo CTFPAD_HEDGEDOC_IS_INTERNAL=1 >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install pip --user --upgrade
          python -m pip install -r requirements.txt --user --upgrade

      - run: |
          python manage.py migrate
          python manage.py test ctfpad
