name: "Run tests"

on:
  workflow_dispatch:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install pip --user --upgrade
          python -m pip install -r requirements.txt --user --upgrade
          python manage.py test ctfpad
